# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='propertyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=40)),
                ('State', models.CharField(max_length=2)),
                ('Zip', models.CharField(max_length=10)),
            ],
        ),
    ]
