# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getMortgage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='status',
            field=models.CharField(default='Not Active', max_length=20),
        ),
    ]
