# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getMortgage', '0002_propertyinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='userName',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
