# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getMortgage', '0004_propertyinfo_requestingamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='status',
            field=models.CharField(default='In Progress', max_length=20),
        ),
    ]
