# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='investmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('requested_funding', models.CharField(max_length=20)),
                ('credit', models.CharField(max_length=4)),
                ('estimated_return', models.CharField(max_length=10)),
                ('status', models.CharField(default='Not Active', max_length=20)),
            ],
        ),
    ]
